version: 2

sources:
  - name: staging_data
    database: NYC_Taxi_Staging  # <--- El nombre del Warehouse de entrada
    schema: dbo
    tables:
      - name: stg_taxis_raw  # <--- El nombre de la tabla
        columns:
          - name: fecha_carga_sistema
            description: "Fecha técnica de inserción en el sistema"
          - name: dim_taxi_zones_raw  # <--- La tabla del Notebook